language: elixir

elixir: 1.5.3

otp_release: 20.0

matrix:
  include:
    - elixir: 1.6.0-rc.1
      otp_release: 20.1
    - elixir: 1.5.3
      otp_release: 20.0
    - elixir: 1.4.4
      otp_release: 19.0

script:
  - mix test
  - MIX_ENV=test mix credo --format=oneline
